/**
 * Prepare CSDM / HLAE / CS2 so TrueView is on and the demo player UI is hidden
 * before the demo loads (demo_ui_mode must be set early — CSDM issue #910).
 */

import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const EARLY_CMDS = [
  "demo_ui_mode 0",
  "cl_demo_predict 2",
  "cl_trueview_show_status 0",
  "spec_autodirector 0",
  "cl_drawhud 1",
  "cl_draw_only_deathnotices 0",
  "crosshair 1",
  "r_drawviewmodel 1",
  "spec_show_xray 0",
];

/**
 * @returns {string} path to HLAE config folder we manage
 */
export function hlaeConfigFolderPath() {
  return join(homedir(), ".csdm", "pov-hlae-cfg");
}

/**
 * Write autoexec so CS2 applies TrueView + hides demoui on launch (before playdemo).
 * @param {(line: string) => void} [onLog]
 */
export function ensureHlaeAutoexec(onLog = () => {}) {
  const root = hlaeConfigFolderPath();
  const cfgDir = join(root, "cfg");
  mkdirSync(cfgDir, { recursive: true });
  const autoexec = join(cfgDir, "autoexec.cfg");
  const body = [
    "// Generated by yt-cs2-demo-to-pov — do not edit while recording",
    ...EARLY_CMDS,
    "host_writeconfig",
    "",
  ].join("\n");
  writeFileSync(autoexec, body, "utf8");
  onLog(`HLAE autoexec ready: ${autoexec}\n`);
  return root;
}

/**
 * Align CSDM settings with POV recording (TrueView on, death-notices-only off, HLAE cfg folder).
 * @param {(line: string) => void} [onLog]
 */
export function ensureCsdmPovSettings(onLog = () => {}) {
  const settingsPath = join(homedir(), ".csdm", "settings.json");
  if (!existsSync(settingsPath)) {
    onLog(`CSDM settings not found at ${settingsPath}\n`);
    return null;
  }

  const cfgRoot = ensureHlaeAutoexec(onLog);
  const settings = JSON.parse(readFileSync(settingsPath, "utf8"));
  if (!settings.video || typeof settings.video !== "object") {
    settings.video = {};
  }
  const video = settings.video;
  let changed = false;

  if (video.trueView !== true) {
    video.trueView = true;
    changed = true;
  }
  if (video.showOnlyDeathNotices !== false) {
    video.showOnlyDeathNotices = false;
    changed = true;
  }
  if (video.showXRay !== false) {
    video.showXRay = false;
    changed = true;
  }
  if (!video.hlae || typeof video.hlae !== "object") {
    video.hlae = {};
  }
  if (video.hlae.configFolderEnabled !== true) {
    video.hlae.configFolderEnabled = true;
    changed = true;
  }
  if (video.hlae.configFolderPath !== cfgRoot) {
    video.hlae.configFolderPath = cfgRoot;
    changed = true;
  }

  if (changed) {
    writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
    onLog(`Updated CSDM settings for POV (TrueView, full HUD, HLAE cfg folder)\n`);
  }
  return settingsPath;
}

/**
 * Inject early tick commands into a CSDM actions JSON (demo.dem.json).
 * Keep this minimal — heavy edits break demo_gototick / sequence cuts.
 * @param {unknown} data
 * @returns {boolean} whether the structure was modified
 */
export function injectEarlyDemoCommands(data) {
  const sequences = Array.isArray(data) ? data : data?.sequences;
  if (!Array.isArray(sequences) || sequences.length === 0) {
    return false;
  }

  let changed = false;
  for (const seq of sequences) {
    if (!seq || !Array.isArray(seq.actions)) {
      continue;
    }
    // Drop legacy demoui toggles that re-open the player bar.
    const before = seq.actions.length;
    seq.actions = seq.actions.filter((a) => {
      const cmd = String(a?.cmd ?? "").trim().toLowerCase();
      return cmd !== "demoui" && !/^demoui\b/.test(cmd);
    });
    if (seq.actions.length !== before) {
      changed = true;
    }

    // Only two early cmds — do not flood setup ticks (breaks gototick).
    for (const cmd of ["demo_ui_mode 0", "cl_demo_predict 2"]) {
      const exists = seq.actions.some(
        (a) => Number(a.tick) <= 96 && String(a.cmd).trim() === cmd,
      );
      if (!exists) {
        seq.actions.unshift({ tick: 96, cmd });
        changed = true;
      }
    }
  }
  return changed;
}

/**
 * Poll demoPath.json and patch TrueView / demoui as soon as CSDM writes it.
 * Stops after the first successful patch to avoid racing CS2 while it reads the file.
 * @param {string} demoPath
 * @param {(line: string) => void} [onLog]
 */
export function startDemoActionsPatcher(demoPath, onLog = () => {}) {
  const actionsPath = `${demoPath}.json`;
  let lastMtime = 0;
  let lastSize = -1;
  let patched = false;

  const timer = setInterval(() => {
    if (patched) {
      return;
    }
    try {
      if (!existsSync(actionsPath)) {
        return;
      }
      const st = statSync(actionsPath);
      if (st.mtimeMs === lastMtime && st.size === lastSize) {
        return;
      }
      lastMtime = st.mtimeMs;
      lastSize = st.size;
      const raw = readFileSync(actionsPath, "utf8");
      const data = JSON.parse(raw);
      if (!injectEarlyDemoCommands(data)) {
        patched = true;
        return;
      }
      writeFileSync(actionsPath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
      patched = true;
      onLog(`Patched demo actions JSON (${actionsPath}) — TrueView + hide demoui\n`);
    } catch {
      // File may be mid-write; retry next tick.
    }
  }, 40);

  return {
    actionsPath,
    stop() {
      clearInterval(timer);
    },
  };
}
